### ISSUE TITLE
AppDaemon not connecting to HA

### ISSUE THREAD

**Issue by jesserockz** [hassio-addons/addon-appdaemon3#23] opened 2018-08-21 08:41 UTC
## Expected behavior

> For AppDaemon to start and connect to HA

## Actual behavior

> AppDemon disconnects from HA as soon as it connects

## Versions

HassOS 1.7
Supervisor 127
HA 0.76.0
AppDaemon Addon 1.4.1

## appdaemon.yaml

```secrets: /config/secrets.yaml
log:
  logfile: STDOUT
  errorfile: STDERR
appdaemon:
  threads: 10
  app_dir: /config/appdaemon/apps
  time_zone: Pacific/Auckland
  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
      ha_key: **REMOVED**
hadashboard:
  dash_url: **REMOVED**
  dash_dir: /config/appdaemon/dashboards
```

## Logs

```
2018-08-21 20:21:06.640902 INFO AppDaemon: HASS: Connected to Home Assistant 0.76.0 
2018-08-21 20:21:06.693647 DEBUG AppDaemon: Event type:ha_disconnected: 
2018-08-21 20:21:06.695088 DEBUG AppDaemon: {} 
2018-08-21 20:21:06.697026 WARNING AppDaemon: HASS: Disconnected from Home Assistant, retrying in 5 seconds 
2018-08-21 20:21:06.698592 WARNING AppDaemon: HASS: ------------------------------------------------------------ 
2018-08-21 20:21:06.700339 WARNING AppDaemon: HASS: Unexpected error: 
2018-08-21 20:21:06.701800 WARNING AppDaemon: HASS: ------------------------------------------------------------ 
2018-08-21 20:21:06.705131 WARNING AppDaemon: HASS: Traceback (most recent call last): 
File "/usr/lib/python3.6/site-packages/appdaemon/plugins/hass/hassplugin.py", line 223, in get_updates 
  result = json.loads(self.ws.recv()) 
File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 302, in recv 
  opcode, data = self.recv_data() 
File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 319, in recv_data 
  opcode, frame = self.recv_data_frame(control_frame) 
File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 332, in recv_data_frame 
  frame = self.recv_frame() 
File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 366, in recv_frame 
  return self.frame_buffer.recv_frame() 
File "/usr/lib/python3.6/site-packages/websocket/_abnf.py", line 383, in recv_frame 
  frame.validate(self.skip_utf8_validation) 
File "/usr/lib/python3.6/site-packages/websocket/_abnf.py", line 162, in validate 
  raise WebSocketProtocolException("rsv is not implemented, yet") 
websocket._exceptions.WebSocketProtocolException: rsv is not implemented, yet 
2018-08-21 20:21:06.706616 WARNING AppDaemon: HASS: ------------------------------------------------------------
```

**Comment by kuradi** [comment] 2018-08-22 20:43
same here after updating 76.3

2018-08-22 23:35:43.154469 WARNING AppDaemon: HASS: ------------------------------------------------------------
2018-08-22 23:35:48.186145 INFO AppDaemon: HASS: Connected to Home Assistant 0.76.2
2018-08-22 23:35:48.650433 DEBUG AppDaemon: Event type:ha_disconnected:
2018-08-22 23:35:48.651620 DEBUG AppDaemon: {}
2018-08-22 23:35:48.653113 DEBUG HADasboard: Sending data to 1 dashes: {'event_type': 'ha_disconnected', 'data': {}}
2018-08-22 23:35:48.654598 DEBUG HADasboard: Found dashboard type Main Panel
2018-08-22 23:35:48.656722 WARNING AppDaemon: HASS: Disconnected from Home Assistant, retrying in 5 seconds
2018-08-22 23:35:48.657836 WARNING AppDaemon: HASS: ------------------------------------------------------------
2018-08-22 23:35:48.659336 WARNING AppDaemon: HASS: Unexpected error:
2018-08-22 23:35:48.660004 WARNING AppDaemon: HASS: ------------------------------------------------------------
2018-08-22 23:35:48.662348 WARNING AppDaemon: HASS: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/plugins/hass/hassplugin.py", line 223, in get_updates
    result = json.loads(self.ws.recv())
  File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 302, in recv
    opcode, data = self.recv_data()
  File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 319, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 332, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/lib/python3.6/site-packages/websocket/_core.py", line 366, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib/python3.6/site-packages/websocket/_abnf.py", line 383, in recv_frame
    frame.validate(self.skip_utf8_validation)
  File "/usr/lib/python3.6/site-packages/websocket/_abnf.py", line 162, in validate
    raise WebSocketProtocolException("rsv is not implemented, yet")
websocket._exceptions.WebSocketProtocolException: rsv is not implemented, yet

**Comment by jesserockz** [comment] 2018-08-22 21:16
It seems to be an issue with appdaemon not sending the auth packet correctly, or the hassio supervisor not giving a correct token or the hassio proxy not handling it correctly. I changed it to communicate directly to HA using the api_password and it works for now. 
So this might not be the correct repo for an issue.

**Comment by engrbm87** [comment] 2018-08-23 14:02
Please let me know how to change it back to use api_password

**Comment by jesserockz** [comment] 2018-08-23 18:04
Replace `http://hassio/homeassistant` with the IP eg: `http://192.168.1.20:8123` 
And put your api password (or secret reference) in `ha_key`

**Comment by frenck** [comment] 2018-08-23 18:07
I would strongly advise against using "other" URLs. Nevertheless, I understand if it is broken it will temporarily fix your setup.

This is the wrong place to raise this issue though. More appropriate reporting location of the above issues would probably be home-assistant/hassio or home-assistant/appdaemon3

My guess this is an issue with the hassio proxy.

**Comment by frenck** [comment] 2018-08-23 18:07
Can anybody provide the logs for the Supervisor at the moment the error happens on the AppDaemon add-on?

**Comment by jesserockz** [comment] 2018-08-23 18:26
Might not be lined properly as I'm on my phone
 ```
18-08-23 18:25:10 INFO (MainThread) [hassio.api.proxy] Home-Assistant Websocket API request initialze 
18-08-23 18:25:10 INFO (MainThread) [hassio.api.proxy] Websocket access from a0d7b954_appdaemon3 
18-08-23 18:25:10 ERROR (MainThread) [hassio.api.proxy] Failed authentication to HomeAssistant websocket 
18-08-23 18:25:14 ERROR (MainThread) [asyncio] Task exception was never retrieved 
future: <Task finished coro=<WebSocketWriter.ping() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py:617> exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0x71a30dc0>; the handler is closed')> 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 621, in ping 
    return await self._send_frame(message, WSMsgType.PING) 
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 603, in _send_frame 
    self.transport.write(header + message) 
  File "uvloop/handles/stream.pyx", line 671, in uvloop.loop.UVStream.write 
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive 
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x71a30dc0>; the handler is closed 
```

**Comment by frenck** [comment] 2018-08-23 18:30
That is a little hard to untangle :P

**Comment by frenck** [comment] 2018-08-24 07:51
Just a thought... Are you guys using the new Auth system?

**Comment by engrbm87** [comment] 2018-08-24 08:05
Yes i have the new Auth enabled. but i also have legacy_api_password enabled as well.

**Comment by jesserockz** [comment] 2018-08-24 08:12
Yes I do have both legacy and new auth enabled

**Comment by pvizeli** [comment] 2018-08-24 16:51
Is that directly after Home Assistant update? Could be that home-assistant isn't ready and it fails? Do it run after you restart the add-on?

**Comment by jesserockz** [comment] 2018-08-24 19:44
I have tried restarting everything all together and individually with different timings

**Comment by pvizeli** [comment] 2018-08-25 06:56
Without legacy module? We don't need this

**Comment by jesserockz** [comment] 2018-08-25 09:46
Ha, works fine when the legacy auth is disabled.

**Comment by engrbm87** [comment] 2018-08-25 10:20
confirmed, working with legacy_api_password disabled

**Comment by frenck** [comment] 2018-08-30 11:02
So in conclusion, this is not an issue with the add-on.
As far as I understand, there is an Hassio  Supervisor update needed for this and is caused by all the new Authentication stuff.

Closing this issue, since there is no work left to do on this add-on for this issue.

**Closed as completed by frenck** 2018-08-30 11:02 UTC
